version: '3.6'

services:
  db:
    image: mysql:5.7
    environment:
        - MYSQL_ALLOW_EMPTY_PASSWORD=yes
        - MYSQL_DATABASE=generatedata

  gd:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - http_proxy=${http_proxy}
        - https_proxy=${https_proxy}
    image: asperitus/generatedata:latest
    depends_on:
      - db
    ports:
      - 8080:80
##